[package]
name = "emurs_loader_desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emurs_kernel = { path = "../../emurs_kernel" }
modular-bitfield = "0.11"
