[target.thumbv4t-nintendo-gba]
rustflags = [
    "--cfg",
    "portable_atomic_unsafe_assume_single_core",
    "-C",
    "link-arg=-Tconfig/thumbv4t-nintendo-gba.ld",
]

[target.mips-nintendo-n64]
rustflags = [
    "-C",
    "link-arg=-Tconfig/mips-nintendo-n64.ld",
]
