on: [push]

name: build

jobs:
  check:
    name: thumbv4t-nintendo-gba build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src

      - shell: bash
        run: ./debug.sh thumbv4t-nintendo-gba
      - shell: bash
        run: ./release.sh thumbv4t-nintendo-gba

      - name: Upload debug build
        uses: actions/upload-artifact@v3
        with:
          name: thumbv4t-nintendo-gba-debug
          path: target/thumbv4t-nintendo-gba/debug/emurs_loader_gba
      - name: Upload release build
        uses: actions/upload-artifact@v3
        with:
          name: thumbv4t-nintendo-gba-release
          path: target/thumbv4t-nintendo-gba/release/emurs_loader_gba